### PR TITLE
025deg jra55do_ryf:update OM3 executable to latest version

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
Changes needed to use latest OM3 executable.

Contributes to https://github.com/COSIMA/access-om3/issues/118

### CODE REVIEW

**Comment by micaeljtoliveira** [comment]
@dougiesquire @anton-seaice @aekiss I'm not entirely sure what's the status of the 0.25deg branch (sorry, I got a bit lost in the middle of all the issues/discussions). Do you think now would be a good time to update the executable? If not, please convert this issue to draft.

**Comment by dougiesquire** [comment]
I think we should merge https://github.com/COSIMA/MOM6-CICE6/pull/48 first

**Comment by anton-seaice** [comment]
I will rebase and test this now, unless someone is working on it already ?

**Comment by anton-seaice** [comment]
I ran this successfully for one month, and it produced history output with no obvious errors.

**Review by anton-seaice — APPROVED** [review]

**Pull request merged**
