### PR TITLE
Cice config (#17)

### PR DESCRIPTION
**Pull request by anton-seaice**
* Update CICE config to match OM2 CICE Config

### CODE REVIEW

**Comment by aekiss** [comment]
LGTM, my only question is whether we should have `use_leap_years`=true for IAF. It was false for both IAF and RYF in ACCESS-OM2 for reasons I no longer recall, but [the calendar manager was updated in CICE6](https://cice-consortium-cice.readthedocs.io/en/main/user_guide/ug_implementation.html#time-manager) so we may need to revisit this. Or does NUOPC handle all the calendar stuff?

**Comment by anton-seaice** [comment]
> LGTM, my only question is whether we should have `use_leap_years`=true for IAF. It was false for both IAF and RYF in ACCESS-OM2 for reasons I no longer recall, but [the calendar manager was updated in CICE6](https://cice-consortium-cice.readthedocs.io/en/main/user_guide/ug_implementation.html#time-manager) so we may need to revisit this. Or does NUOPC handle all the calendar stuff?

I'll investigate - I am pretty sure this config field is used, and we have leap years in the forcing, so you are probably right.

**Comment by anton-seaice** [comment]
It looks like `ice_calendar` is set by NUOPC:

https://github.com/CICE-Consortium/CICE/blob/b14cedfaed8b81500fc5422cfc44b6d80e5893ef/cicecore/drivers/nuopc/cmeps/ice_comp_nuopc.F90#L487

https://github.com/CICE-Consortium/CICE/blob/b14cedfaed8b81500fc5422cfc44b6d80e5893ef/cicecore/shared/ice_calendar.F90#L214

but `days_per_year` and `use_leap_years` are not.

Which means the model runs, but some of the attributes/comments are wrong in the output if its not set (this may be the only impact):

https://github.com/CICE-Consortium/CICE/blob/b14cedfaed8b81500fc5422cfc44b6d80e5893ef/cicecore/cicedyn/infrastructure/io/io_pio2/ice_history_write.F90#L227

https://github.com/CICE-Consortium/CICE/blob/b14cedfaed8b81500fc5422cfc44b6d80e5893ef/cicecore/cicedyn/infrastructure/io/io_pio2/ice_history_write.F90#L652

I doubt those matter, however maybe some analysis scripts would try and automatically parse that field. Either way, we should set it :)

**Comment by anton-seaice** [comment]
Merged in #25

**Pull request closed without merging**
