### PR TITLE
Update cice blocks to suit the new PE layout

### PR DESCRIPTION
**Pull request by minghangli-uni**
See https://github.com/COSIMA/access-om3/issues/210

### CODE REVIEW

**Review by dougiesquire — APPROVED** [review]
Thanks @minghangli-uni. LGTM and runs as is.

**Review by dougiesquire — CHANGES_REQUESTED** [review]
Actually wait maybe it didn't run

**Review by dougiesquire — APPROVED** [review]
No, it did (too many simultaneous reviews on the go). Please feel free to merge

**Comment by anton-seaice** [comment]
I will double check the cice logs too :)

**Comment by anton-seaice** [comment]
This looks good :)

**Review by anton-seaice — APPROVED** [review]

**Comment by minghangli-uni** [comment]
Thanks @anton-seaice

**Comment by minghangli-uni** [comment]
!cherry-pick 2bc6107 1deg_jra55do_iaf 1deg_jra55do_ryf_wombatlite

**Comment by minghangli-uni** [comment]
!cherry-pick 2bc6107 into 1deg_jra55do_iaf 1deg_jra55do_ryf_wombatlite

**Pull request merged**
