### PR TITLE
Add comments after ocn_cpl_dt in nuopc.runconfig 

### PR DESCRIPTION
**Pull request by minghangli-uni**
See https://github.com/COSIMA/access-om3/issues/157, https://github.com/COSIMA/access-om3/issues/157#issuecomment-2249623984

### CODE REVIEW

**Review by aekiss — APPROVED** [review]
LGTM, thanks @minghangli-uni

**Comment by minghangli-uni** [comment]
!cherry-pick ad59cb2 into 1deg_jra55do_iaf 0.25deg_jra55do_ryf

**Comment by aekiss** [comment]
you need to use the merge/rebase commit hash, i.e. 18d4dbb

**Comment by minghangli-uni** [comment]
!cherry-pick https://github.com/COSIMA/MOM6-CICE6/commit/18d4dbb18944e67ccb24869c9d70950821219645  into 1deg_jra55do_iaf 0.25deg_jra55do_ryf

**Comment by minghangli-uni** [comment]
!cherry-pick 18d4dbb into 1deg_jra55do_iaf 0.25deg_jra55do_ryf

**Comment by minghangli-uni** [comment]
!cherry-pick 18d4dbb into 1deg_jra55do_iaf 025deg_jra55do_ryf

**Pull request merged**
