### PR TITLE
1deg_jra55do_iaf: Update OM3 executable to latest version

### PR DESCRIPTION
**Pull request by micaeljtoliveira**
This implements a new naming scheme for the exec path.

Contributes to https://github.com/COSIMA/access-om3/issues/118

### CODE REVIEW

**Review by dougiesquire — APPROVED** [review]
Great - nice to have the git tag so easy to find

**Comment by dougiesquire** [comment]
Actually, can you hold off on merging. Should probably do a test run

**Comment by dougiesquire** [comment]
Ran successfully 👍

**Comment by micaeljtoliveira** [comment]
> Thanks @micaeljtoliveira, looks good to me. But it could be neater and easier to visually compare with the github commit history if you used a short hash (7 chars).
> 
> Would it be useful to also include the commit date?
> 
> I guess 5pjh7z2 is the spack hash, but what purpose does "main" serve? Could drop if it's redundant.

I'm afraid we don't have much control over all this. The information that can be used by Spack in install paths is very limited (compiler, architecture, package name, version, spack hash). So no date here.

This part of the path `access-om3-d6813d6b9e1df560ac3f6ba6a605daab9cfd9569_main-5pjh7z2` corresponds to `{package-name}-{package-version}-{spack-hash-7}`. 

`main` is part of the version and is the package version that corresponds to this commit. You can read all about it [here](https://spack.readthedocs.io/en/latest/basic_usage.html#git-versions), but to make it short, this is necessary and the default used by spack is even worse (here it would be something like `0.2.0.git.20`, which means "20 commits after tag 0.2.0").

I think one could shorten the git commit hash, but then people might easily confused it with the spack hash, so I'm not sure that's a good idea.

**Comment by micaeljtoliveira** [comment]
@aekiss I think for now this is the best we can do (see explanation above). I'll proceed with merging so we can move forward. If needed, the length of the git hash can be shortened next time we install a new version.

**Pull request merged**
